In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv('/kaggle/input/datasets/nabinpaaudel/carsdata/cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [2]:
df['brand'].nunique()

32

# One HOT Encoding

In [3]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# K-1 One Hot Encoding

In [4]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)# the first column will get removed

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# ONE HOT ENCODING USING SKLEARN

In [5]:
X=df.iloc[:,0:4]
y=df['selling_price']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [19]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=int)
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])
X_test_new=ohe.fit_transform(X_test[['fuel','owner']])

In [20]:
print(X_train_new)

[[1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]]

In [21]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Honda', 100000, 1, ..., 1, 0, 0],
       ['Maruti', 120000, 1, ..., 1, 0, 0],
       ['Renault', 100000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 70000, 0, ..., 0, 0, 0],
       ['Maruti', 110000, 1, ..., 1, 0, 0],
       ['Maruti', 65755, 0, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

# OneHotEncoding with top categories

In [29]:
counts=df['brand'].value_counts()

In [31]:
df['brand'].nunique()
threshold=100
repl=counts[counts<=threshold].index

In [33]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0