In [1]:
import numpy as np 
import pandas as pd
df=pd.read_csv('/kaggle/input/datasets/nabinpaaudel/customer/customer.csv')
df.sample(5)

    age  gender   review education purchased
49   25  Female     Good        UG        No
4    16  Female  Average        UG        No
18   19    Male     Good    School        No
45   61    Male     Poor        PG       Yes
6    18    Male     Good    School        No

In [2]:
df=df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [3]:
X = df[['review', 'education']] 
y = df['purchased']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [4]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[
    ['Poor', 'Average', 'Good'],  # Matches 'review' column
    ['School', 'UG', 'PG']         # Matches 'education' column
])

In [5]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [6]:
X_train

     review education
32  Average        UG
39     Poor        PG
21  Average        PG
36     Good        UG
19     Poor        PG
42     Good        PG
49     Good        UG
26     Poor        PG
22     Poor        PG
13  Average    School
41     Good        PG
17     Poor        UG
45     Poor        PG
24  Average        PG
23     Good    School
4   Average        UG
33     Good        PG
14     Poor        PG
30  Average        UG
10     Good        UG
28     Poor    School
44  Average        UG
34  Average    School
18     Good    School
20  Average    School
25     Good    School
6      Good    School
7      Poor    School
47     Good        PG
1      Poor        UG
16     Poor        UG
0   Average    School
15     Poor        UG
5   Average    School
11     Good        UG
9      Good        UG
8   Average        UG
12     Poor    School
43     Poor        PG
37  Average        PG

In [7]:
new_X_train=oe.transform(X_train)
new_X_test=oe.transform(X_test)

In [8]:
new_X_train

array([[1., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 2.]])

In [9]:
new_X_test

array([[0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [0., 0.]])

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [11]:
le.fit(y_train)

LabelEncoder()

In [12]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [13]:
new_y_train=le.transform(y_train)
new_y_test=le.transform(y_test)

In [14]:
new_y_train

array([1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1])