In [1]:
import pandas as pd
df=pd.read_csv('/kaggle/input/datasets/nabinpaaudel/pokemon-dataset/pokemon_data.csv')

# 1.How big is the data

In [3]:
df.shape

(800, 12)

# 2.How does the data look like

In [4]:
df.head()# it provides top 5 data
df.sample(5)# it provides  random datasets from any where 5 for 5 datasets

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
115,107,Hitmonchan,Fighting,NaN,50,105,79,35,110,76,1,False
289,266,Silcoon,Bug,NaN,50,35,55,25,25,15,3,False
313,289,Slaking,Normal,NaN,150,160,100,95,65,100,3,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,5,False

# 3.what is the data type of columns

In [5]:
df.info() # it provides the information about columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

# 4.Are there any missing values?

In [6]:
df.isnull().sum() # used to find number of null values in my datasets

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

# 5.How does the data look mathematically

In [7]:
df.describe() # provide mathematical summary of my datasets

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

# 6.Are there dupicate values

In [8]:
df.duplicated().sum()

np.int64(0)

# 7.How is the correlation between the columns

In [12]:
numeric_data=df.select_dtypes(include='number')
numeric_data.corr() # it provides the correlation between the columns

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
#,1.000000,0.097614,0.102298,0.094786,0.088759,0.085817,0.010733,0.982516
HP,0.097614,1.000000,0.422386,0.239622,0.362380,0.378718,0.175952,0.058683
Attack,0.102298,0.422386,1.000000,0.438687,0.396362,0.263990,0.381240,0.051451
Defense,0.094786,0.239622,0.438687,1.000000,0.223549,0.510747,0.015227,0.042419
Sp. Atk,0.088759,0.362380,0.396362,0.223549,1.000000,0.506121,0.473018,0.036437
Sp. Def,0.085817,0.378718,0.263990,0.510747,0.506121,1.000000,0.259133,0.028486
Speed,0.010733,0.175952,0.381240,0.015227,0.473018,0.259133,1.000000,-0.023121
Generation,0.982516,0.058683,0.051451,0.042419,0.036437,0.028486,-0.023121,1.000000

In [13]:
numeric_data.corr()['Attack'] # it provides the correlation between attack and other columns

#             0.102298
HP            0.422386
Attack        1.000000
Defense       0.438687
Sp. Atk       0.396362
Sp. Def       0.263990
Speed         0.381240
Generation    0.051451
Name: Attack, dtype: float64