In [1]:
import pandas as pd
df=pd.read_csv('/kaggle/input/datasets/nabinpaaudel/pokemon-dataset/pokemon_data.csv')

In [2]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

# Complex Indexing(.loc[] and .iloc[])

In [7]:
 print(df.loc[5,['Attack','Legendary']]) #df.loc[row_label, column_label]

Attack          64
Legendary    False
Name: 5, dtype: object

In [9]:
 print(df.loc[5,['Legendary']])

Legendary    False
Name: 5, dtype: object

In [10]:
print(df.loc[50:52,['Type 1','Type 2']])

   Type 1  Type 2
50  Grass  Poison
51    Bug   Grass
52    Bug   Grass

In [12]:
print(df.iloc[1,3]) # gives the first row fourth column

Poison

In [13]:
print(df.iloc[0:2,2:4])

  Type 1  Type 2
0  Grass  Poison
1  Grass  Poison

In [15]:
print(df.iloc[:,7:9]) # gives all the rows of seventh and eight columns

     Sp. Atk  Sp. Def
0         65       65
1         80       80
2        100      100
3        122      120
4         60       50
..       ...      ...
795      100      150
796      160      110
797      150      130
798      170      130
799      130       90

[800 rows x 2 columns]

In [18]:
print(df.iloc[103,:]) # gives all the columns of  row 103

#                 95
Name            Onix
Type 1          Rock
Type 2        Ground
HP                35
Attack            45
Defense          160
Sp. Atk           30
Sp. Def           45
Speed             70
Generation         1
Legendary      False
Name: 103, dtype: object

In [17]:
print(df.iloc[[103],:])# gives all the columns of row 103 as same orientation in the dataset .easier to look

      #  Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
103  95  Onix   Rock  Ground  35      45      160       30       45     70

     Generation  Legendary
103           1      False

# Groupby and Aggregation

In [21]:
print(df.groupby('Type 1').mean(numeric_only=True))

                   #         HP      Attack     Defense    Sp. Atk    Sp. Def  \
Type 1
Bug       334.492754  56.884058   70.971014   70.724638  53.869565  64.797101
Dark      461.354839  66.806452   88.387097   70.225806  74.645161  69.516129
Dragon    474.375000  83.312500  112.125000   86.375000  96.843750  88.843750
Electric  363.500000  59.795455   69.090909   66.295455  90.022727  73.704545
Fairy     449.529412  74.117647   61.529412   65.705882  78.529412  84.705882
Fighting  363.851852  69.851852   96.777778   65.925926  53.111111  64.703704
Fire      327.403846  69.903846   84.769231   67.769231  88.980769  72.211538
Flying    677.750000  70.750000   78.750000   66.250000  94.250000  72.500000
Ghost     486.500000  64.437500   73.781250   81.187500  79.343750  76.468750
Grass     344.871429  67.271429   73.214286   70.800000  77.500000  70.428571
Ground    356.281250  73.781250   95.750000   84.843750  56.468750  62.750000
Ice       423.541667  72.000000   72.750000   71.416667  77.541667  76.291667
Normal    319.173469  77.275510   73.469388   59.846939  55.816327  63.724490
Poison    251.785714  67.250000   74.678571   68.821429  60.428571  64.392857
Psychic   380.807018  70.631579   71.456140   67.684211  98.403509  86.280702
Rock      392.727273  65.363636   92.863636  100.795455  63.340909  75.477273
Steel     442.851852  65.222222   92.703704  126.370370  67.518519  80.629630
Water     303.089286  72.062500   74.151786   72.946429  74.812500  70.517857

               Speed  Generation  Legendary
Type 1
Bug        61.681159    3.217391   0.000000
Dark       76.161290    4.032258   0.064516
Dragon     83.031250    3.875000   0.375000
Electric   84.500000    3.272727   0.090909
Fairy      48.588235    4.117647   0.058824
Fighting   66.074074    3.370370   0.000000
Fire       74.442308    3.211538   0.096154
Flying    102.500000    5.500000   0.500000
Ghost      64.343750    4.187500   0.062500
Grass      61.928571    3.357143   0.042857
Ground     63.906250    3.156250   0.125000
Ice        63.458333    3.541667   0.083333
Normal     71.551020    3.051020   0.020408
Poison     63.571429    2.535714   0.000000
Psychic    81.491228    3.385965   0.245614
Rock       55.909091    3.454545   0.090909
Steel      55.259259    3.851852   0.148148
Water      65.964286    2.857143   0.035714

In [23]:
clean_summary=df.groupby('Type 2').agg(
    avg_hp=('HP','mean'),
    total_pokemon=('Name','count'),
    highest_attack=('Attack','max')
)
clean_summary

             avg_hp  total_pokemon  highest_attack
Type 2
Bug       53.333333              3             125
Dark      75.550000             20             164
Dragon    82.166667             18             130
Electric  88.166667              6             150
Fairy     64.304348             23             160
Fighting  79.461538             26             190
Fire      71.250000             12             180
Flying    71.391753             97             180
Ghost     59.142857             14             150
Grass     62.640000             25             110
Ground    77.228571             35             170
Ice       90.000000             14             170
Normal    63.500000              4              68
Poison    58.764706             34             150
Psychic   72.212121             33             145
Rock      68.071429             14             140
Steel     64.636364             22             150
Water     62.714286             14             115